export const categorias = {
  0: "Romance",
  1: "Fantasia",
  2: "Ficção Científica",
  3: "Mistério",
  4: "Terror",
  5: "Distopia",
  6: "Aventura",
  7: "Poesia",
  8: "Biografia",
  9: "História",
  10: "Filosofia",
  11: "Ciências",
  12: "Tecnologia",
  13: "Educação",
  14: "Auto Ajuda",
  15: "Religião",
  16: "Infantil",
  17: "Juvenil",
  18: "Didático",
};