// <auto-generated />
using BibliotecaSR.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BibliotecaSR.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324192301_M01")]
    partial class M01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BibliotecaSR.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "charlie@gmail.com",
                            Nome = "Charlie",
                            Perfil = 0,
                            Senha = "$2a$11$2ETt9/wToZgZd5NOR4AZROHpvMWwrzSMYbbnJJkEur4AaGISK0Lvy"
                        },
                        new
                        {
                            Id = 2,
                            Email = "geovana@gmail.com",
                            Nome = "Geovana",
                            Perfil = 1,
                            Senha = "$2a$11$6PAugevBqTqrfKPgQyvOGONZ3vXrNVaZvHUgF9EtMezQ3rpfTRDRW",
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            Email = "maria@gmail.com",
                            Nome = "Maria",
                            Perfil = 1,
                            Senha = "$2a$11$nj5xtOPG4.h1oRi7hg10vOzGZwYrUaYnMo6Dk.xPfrea6EYRTg4P.",
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            Email = "rodrigo@gmail.com",
                            Nome = "Rodrigo",
                            Perfil = 1,
                            Senha = "$2a$11$krSnweECHsBVNdsz9UKjsOfe/UiqbsPbqwNMHvKiVyoNZYjKPH0oW",
                            Status = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
